[package]
name = "pyo3"
version = "0.1.0"
authors = ["hanshoi <antti.ruotsalainen@hanshoi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "*"